# Generated by Django 2.2.3 on 2019-07-25 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tanggalAbsen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_1', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_2', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_3', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_4', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_5', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_6', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_7', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_8', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_9', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_10', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_11', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_12', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_13', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_14', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_15', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_16', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_17', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_18', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_19', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_20', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_21', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_22', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_23', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_24', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_25', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_26', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_27', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_28', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_29', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_30', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
                ('tgl_31', models.CharField(choices=[('M', 'Masuk'), ('A', 'alpa'), ('I', 'IZIN'), ('S', 'SAKIT'), ('L', 'Libur')], max_length=10, null=True)),
            ],
            options={
                'db_table': 'tanggalAbsen',
            },
        ),
        migrations.CreateModel(
            name='bulanAbsen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bulan', models.CharField(choices=[('Januari', 'Januari'), ('Februari', 'Februari'), ('Maret', 'Maret'), ('April', 'April'), ('Mei', 'Mei'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('Agustus', 'Agustus'), ('September', 'September'), ('Oktober', 'Oktober'), ('November', 'November'), ('Desember', 'Desember')], max_length=255)),
                ('nama_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.siswa')),
                ('tanggal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absen.tanggalAbsen')),
            ],
            options={
                'db_table': 'bulanAbsen',
            },
        ),
    ]
