# Generated by Django 2.2.3 on 2019-07-25 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tagihan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spp', models.CharField(blank=True, max_length=255, null=True)),
                ('osis', models.CharField(blank=True, max_length=255, null=True)),
                ('lain1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lain-lain')),
                ('lain2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lain-lain')),
                ('lain3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lain-lain')),
                ('lain4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lain-lain')),
                ('lain5', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lain-lain')),
                ('lain6', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lain-lain')),
                ('lain7', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lain-lain')),
                ('namaSiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.siswa')),
            ],
            options={
                'db_table': 'tagihanSiswa',
            },
        ),
    ]
